apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-wars-api-deployment
spec:
  selector:
    matchLabels:
      app: star-wars-api
  replicas: 1
  template:
    metadata:
      labels:
        app: star-wars-api
    spec:
      containers:
      - name: star-wars-api
        image: fernandohfs/star-wars-api:1.1.0
        ports:
        - containerPort: 5000